import 'package:flutter/cupertino.dart';
import 'package:flutter_hooks/flutter_hooks.dart';

class MainScreen extends HookWidget {
  const MainScreen({super.key});

  @override
  Widget build(BuildContext context) {
    useAutomaticKeepAlive();
    return SingleChildScrollView(
      child: Column(
        children: const [
          Text('AAAAAAA'),
          Text('AAAAAAA'),
          Text('AAAAAAA'),
          Text('AAAAAAA'),
          Text('AAAAAAA'),
          Text('AAAAAAA'),
          Text('AAAAAAA'),
          Text('AAAAAAA'),
          Text('AAAAAAA'),
          Text('AAAAAAA'),
          Text('AAAAAAA'),
          Text('AAAAAAA'),
          Text('AAAAAAA'),
          Text('AAAAAAA'),
          Text('AAAAAAA'),
          Text('AAAAAAA'),
          Text('AAAAAAA'),
          Text('AAAAAAA'),
          Text('AAAAAAA'),
          Text('AAAAAAA'),
          Text('AAAAAAA'),
          Text('AAAAAAA'),
          Text('AAAAAAA'),
          Text('AAAAAAA'),
          Text('AAAAAAA'),
          Text('AAAAAAA'),
          Text('AAAAAAA'),
          Text('AAAAAAA'),
          Text('AAAAAAA'),
          Text('AAAAAAA'),
          Text('AAAAAAA'),
          Text('AAAAAAA'),
          Text('AAAAAAA'),
          Text('AAAAAAA'),
          Text('AAAAAAA'),
          Text('AAAAAAA'),
          Text('AAAAAAA'),
          Text('AAAAAAA'),
          Text('AAAAAAA'),
          Text('AAAAAAA'),
          Text('AAAAAAA'),
          Text('AAAAAAA'),
          Text('AAAAAAA'),
          Text('AAAAAAA'),
          Text('AAAAAAA'),
          Text('AAAAAAA'),
          Text('AAAAAAA'),
          Text('AAAAAAA'),
          Text('AAAAAAA'),
          Text('AAAAAAA'),
          Text('AAAAAAA'),
          Text('AAAAAAA'),
          Text('AAAAAAA'),
          Text('AAAAAAA'),
          Text('AAAAAAA'),
          Text('AAAAAAA'),
          Text('AAAAAAA'),
          Text('AAAAAAA'),
          Text('AAAAAAA'),
          Text('AAAAAAA'),
          Text('BBBBBBB'),
          Text('BBBBBBB'),
          Text('BBBBBBB'),
          Text('BBBBBBB'),
        ],
      ),
    );
  }
}
